### ISSUE TITLE
blog not found

### ISSUE THREAD

**Issue by xjvs** [RustPython/rustpython.github.io#11]
In https://github.com/RustPython/RustPython/blob/master/parser/README.md:

It said:
```
We wrote [a blog post](https://rustpython.github.io/featured/2020/03/11/thing-explainer-parser.html) with screenshots and an explanation to help you understand the steps by seeing them in action.
```
But that url returns 404.

Also, seems only the latest blog post is accessible from https://rustpython.github.io/blog, any way to visit older blog posts?

**Comment by coolreader18** [comment]
I think that's just left over from sample text that was there; it'll probably get replaced once we do write an article explaining the parser.

> Also, seems only the latest blog post is accessible from https://rustpython.github.io/blog, any way to visit older blog posts?

So far we do only have one blog post :sweat_smile:

**Comment by mireille-raad** [comment]
@coolreader18 , i had that post as a draft in a previous pull request, I re-submitted. https://github.com/RustPython/rustpython.github.io/pull/14

Can you take a look at the post and see if it is valid?

**Comment by mireille-raad** [comment]
@xjvs here is the blog post - we merged the pull request 

https://rustpython.github.io/2020/04/02/thing-explainer-parser.html 

Sorry this is more of an introduction. If you can write up something more detailed or a "how to contribute guide" to the parser, that would be neat.

**Comment by xjvs** [comment]
Cool, thanks, this is very helpful for understanding how RustPython is implemented.
I opened a PR https://github.com/RustPython/RustPython/pull/1958 to fix the blog link in README.md
