### ISSUE TITLE
Create a webpage to display benchmarks

### ISSUE THREAD

**Issue by theangryhobbit** [RustPython/rustpython.github.io#42]
[This issue (2396)](https://github.com/RustPython/RustPython/issues/2396) on the RustPython repo mentions the creation of a webpage to show a set of benchmarks that are being committed (thus saved) to this repo on a monthly basis.

This issue addressed the creation of such a webpage.

**Comment by mireille-raad** [comment]
@theangryhobbit thank you for creating the page. Should we close the issue or do you want to add something else to the page?

**Comment by theangryhobbit** [comment]
@mireille-raad You're welcome, it was my pleasure 😄 
We can close this issue 👍
