### ISSUE TITLE
no "learn more" section as referenced in the homepage text

### ISSUE THREAD

**Issue by deronnax** [RustPython/rustpython.github.io#47]
On the home page:

> Check out the “learn more” section 

But there is no such section. I had a quick look but I am really not sure what the author was originally referring to.

**Comment by mireille-raad** [comment]
Hey!

I just re-read the section... it says: 

> Check out the “learn more” section for an explainer of all those jargon-y words, or read the blog for more in-depth technical discussion.

I will remove the "learn more" reference and just link to the blog on https://rustpython.github.io/blog

The website doesn't have a lot of information. It is a work in progress. @deronnax:  do you have a topic that you want to learn about? if you have some ideas for content or requests, that could be something we can collaborate on.

**Comment by mireille-raad** [comment]
@deronnax -- i am sorry this took so long to fix. I gave up plans to add the learn more section and I just submitted a PR to remove it.
