### ISSUE TITLE
Incorrect code snippet rendering in how-to-contribute-by-cpython-unittest.html

### ISSUE THREAD

**Issue by tai271828** [RustPython/rustpython.github.io#54]
The following code snippet is not rendered correctly. It should be some thing like this: `USTPYTHONPATH=Lib cargo run --release ./Lib/test/test_unicode.py` (double-dash and grey `background`)

![Selection_550](https://user-images.githubusercontent.com/3217432/143688187-9beaa874-5700-423f-8f71-cae42d491b82.png)

I checked the markdown syntax with my Atom editor and it looks good. Maybe something else causes the rendering incorrectly.

**Comment by youknowone** [comment]
Thank you for the report!

The referred document is: https://rustpython.github.io/blog/2020/04/04/how-to-contribute-by-cpython-unittest.html

**Comment by youknowone** [comment]
For the document itself, I fixed it by fixing the document itself here: https://github.com/RustPython/rustpython.github.io/commit/f962c172e66dd36dec9a80dec739d6a6be86c5b9

**Comment by mireille-raad** [comment]
<img width="990" alt="Screen Shot 2021-12-01 at 1 42 46 PM" src="https://user-images.githubusercontent.com/521705/144294448-61668363-c748-43d9-9949-546440dcad73.png">

Does this work? should we close the issue?

**Comment by tai271828** [comment]
In my opinion, this issue is resolved. Thanks for fixing and confirmation.

**Comment by mireille-raad** [comment]
of course. Always create issues if you have ideas for content or general improvements.

**Comment by youknowone** [comment]
The renderer bug itself is not fixed, but document bug is fixed
