### ISSUE TITLE
The cargo command to install RustPython in the frontpage won't work

### ISSUE THREAD

**Issue by aognio** [RustPython/rustpython.github.io#74]
One of the installation methods suggested is this:

```
cargo install --git https://github.com/RustPython/RustPython
```

But this command won't work, at least with cargo 1.79.0 (ffa9cf99a 2024-06-03) that asks to indicate the package name since there are multiple `Cargo.toml` files inside the repo.

This command instead seems to work well:

```
cargo install --git https://github.com/RustPython/RustPython rustpython
```

That's (I think) because the package name as defined in line 2 of the main `Cargo.toml` file of the repo is `rustpython`:

https://github.com/RustPython/RustPython/blob/main/Cargo.toml#L2

**Comment by aognio** [comment]
Also, mentioning that build needs to be with a nightly version of  `cargo` is important.

**Comment by coolreader18** [comment]
I can't seem to reproduce a build failure on non-nightly compilers, but I've updated the installation instructions! Thanks for bringing this to our attention!
